### ISSUE TITLE
错误	CS0452

### ISSUE THREAD

**Issue by KrystianLi** [lele8/mscan#2]
使用vs2017编译项目
在lib\krb_structures\pac\LogonInfo.cs文件
第28行
mh.WriteReferent(KerbValidationInfo, new Action<_KERB_VALIDATION_INFO>(mh.WriteStruct));

出现以下错误 
错误	CS0452	类型“_KERB_VALIDATION_INFO”必须是引用类型才能用作泛型类型或方法“NdrMarshalBuffer.WriteReferent<T>(T, Action<T>)”中的参数“T”	mscan

**Comment by lele8** [comment]
我使用vs2022编译没出现这个问题
