### ISSUE TITLE
System.NullReferenceException:“未将对象引用设置到对象的实例。” 编译报错

### ISSUE THREAD

**Issue by h2so0o4** [lele8/mscan#3]
System.NullReferenceException:“未将对象引用设置到对象的实例。”
![image](https://user-images.githubusercontent.com/49434585/188316776-dcd8a734-7dee-4472-9dee-3e12c2544abf.png)

**Comment by lele8** [comment]
直接生成解决方案也是这样？

**Comment by lele8** [comment]
你调试好歹加个参数啊，你机器又不在域内
